AWSTemplateFormatVersion: 2010-09-09
Description: 'Template containing all the once-in-an-account configurations for dev accounts'

Parameters:
  SlackInfo:
    Type: String
    Description: <slack workspace id>:<slack channel id>. 'team_notifiche_dev_alarm' by default
    Default: TQSBH3ZS4:C030L43BXGE
  
Resources:

  ###                          DEFINE ALARM TOPIC                          ###
  ############################################################################
  # - Everything written to this topic is an alarm
  AlarmSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: 'dev account alarms topic: send to SQS and slack'
  
  # - Alarm message queue
  AlarmHistoryBufferQueue:
    Type: AWS::SQS::Queue  

  # - Alarm message queue subscription
  AlarmSNSTopicToSqsHistoryBuffer:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt AlarmHistoryBufferQueue.Arn
      Region: !Ref AWS::Region
      TopicArn: !Ref AlarmSNSTopic
  
  # - Alarm message queue policy that grant write right to SNS
  AlarmSNSTopicToSqsHistoryPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Ref AlarmHistoryBufferQueue
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "sns.amazonaws.com"
            Action: "sqs:SendMessage"
            Resource: !Sub ${AlarmHistoryBufferQueue.Arn}
            Condition: 
              ArnEquals: 
                aws:SourceArn: !Ref AlarmSNSTopic
      
  # - Connect dev alarm to slack developers channel
  # AlarmSNSTopicSlackConnection:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sns-topic-to-slack-channel.yaml"
  #     Parameters:
  #       TopicName: 'dev_alarm'
  #       SNSTopicArn: !Ref AlarmSNSTopic
  #       SlackInfo: !Ref SlackInfo
  
Outputs:

  AlarmSNSTopicArn:
    Value: !Ref AlarmSNSTopic
    Description: ARN of the Alarm SNS Topic
  
  AlarmSNSTopicName:
    Value: !GetAtt  AlarmSNSTopic.TopicName
    Description: Name of the Alarm SNS Topic

