AWSTemplateFormatVersion: '2010-09-09'
Description: SPID Hub - Cache


Parameters:

  Project:
    Description: The project
    MinLength: 3
    Type: String

  Environment:
    Description: The enviroment
    MinLength: 3
    Type: String
    AllowedValues:
    - dev
    - uat
    - prod
    - svil
    - coll

  VpcId:
    Description: The VPC in which deploy the service
    Type: AWS::EC2::VPC::Id

  Subnets:
    Description: The Data Subnets in which deploy the service
    Type: List<AWS::EC2::Subnet::Id>

  CacheNumberReplicas:
    Type: String
    Description: Number of Replicas for Redis
    Default: 1

  CacheNodeType:
    Default: cache.t3.small
    Description: The compute and memory capacity of the nodes
    Type: String

  AlarmSNSTopicName:
    Type: String
    Description: "A name of an SNS topic where to send alarm." 

  CPUUtilizationThreshold:
    Type: Number
    Description: The threshold percentage of CPU usage.
    MinValue: 0
    MaxValue: 100
    Default: 60

  EngineCPUUtilizationThreshold:
    Type: Number
    Description: The threshold percentage of CPU utilization of the Redis engine thread
    MinValue: 0
    MaxValue: 100
    Default: 60

  RedisMemoryUsedThreshold:
    Type: Number
    Description: The threshold percentage for the amount of memory utilized.
    MinValue: 0
    MaxValue: 100
    Default: 60

  CurrentConnectionsThreshold:
    Type: Number
    Description: "The threshold number of concurrent and active connections. (Max connections: 65000)."
    MinValue: 0
    MaxValue: 65000
    Default: 60000

Conditions:
  AlarmEnabled: !Not
    - !Equals
      - !Ref AlarmSNSTopicName
      - ""

Resources:

  Redis:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      AtRestEncryptionEnabled: true
      AuthToken:
        Fn::Sub: "{{resolve:secretsmanager:${AuthToken}:SecretString:AuthToken}}"
      AutomaticFailoverEnabled: false
      AutoMinorVersionUpgrade: true
      CacheNodeType:
        Ref: CacheNodeType
      CacheParameterGroupName:
        Ref: RedisNoClusterParameterGroup
      CacheSubnetGroupName:
        Ref: SubnetGroup
      Engine: redis
      EngineVersion: '6.2'
      LogDeliveryConfigurations:
      - DestinationDetails:
          CloudWatchLogsDetails:
            LogGroup:
              Ref: LogGroup
        DestinationType: cloudwatch-logs
        LogFormat: text
        LogType: engine-log
      MultiAZEnabled: false
      # NumCacheClusters: 1
      ReplicasPerNodeGroup: !Ref CacheNumberReplicas
      Port: 6379
      PreferredMaintenanceWindow: sun:23:00-mon:01:30
      ReplicationGroupDescription:
        Fn::Sub: "${Project}-${Environment}"
      SecurityGroupIds:
      - Ref: SecurityGroup
      SnapshotRetentionLimit: 5
      SnapshotWindow: 05:00-09:00
      TransitEncryptionEnabled: true

  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description:
        Fn::Sub: "${Project}-${Environment}-data"
      SubnetIds:
        Ref: Subnets

  RedisNoClusterParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      CacheParameterGroupFamily: redis6.x
      Description:
        Fn::Sub: "${Project}-${Environment}"
      Properties:
        cluster-enabled: 'no'

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: "${Project}-${Environment}-cache"
      RetentionInDays: 14

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Redis
      VpcId:
        Ref: VpcId

  AuthToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        ExcludePunctuation: true
        SecretStringTemplate: '{}'
        GenerateStringKey: "AuthToken"
        PasswordLength: 26
        IncludeSpace: false
      Name:
        Fn::Sub: "${Project}-${Environment}-cache"

  RedisEngineCPUAlarm:
    Condition: AlarmEnabled
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Project}-${Environment}-EngineCPUUtilization
      AlarmDescription: "CloudWatch alarm for Redis Engine CPU Unilization."
      AlarmActions: 
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      InsufficientDataActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      OKActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      DatapointsToAlarm: 1
      Dimensions: 
        - Name: CacheClusterId
          Value: !Sub '${Redis}-001'
      MetricName: EngineCPUUtilization
      Namespace: AWS/ElastiCache
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Statistic: Sum
      Threshold: !Ref EngineCPUUtilizationThreshold
      TreatMissingData: missing

  RedisCPUUtilizationAlarm:
    Condition: AlarmEnabled
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Project}-${Environment}-CPUUtilization
      AlarmDescription: "CloudWatch alarm for Redis  CPU Unilization."
      AlarmActions: 
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      InsufficientDataActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      OKActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      DatapointsToAlarm: 1
      Dimensions: 
        - Name: CacheClusterId
          Value: !Sub '${Redis}-001'
      MetricName: CPUUtilization
      Namespace: AWS/ElastiCache
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Statistic: Sum
      Threshold: !Ref CPUUtilizationThreshold
      TreatMissingData: missing

  RedisMemoryUtilizationAlarm:
    Condition: AlarmEnabled
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Project}-${Environment}-MemoryUsage
      AlarmDescription: "CloudWatch alarm for Redis  Memory usage."
      AlarmActions: 
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      InsufficientDataActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      OKActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      DatapointsToAlarm: 1
      Dimensions: 
        - Name: CacheClusterId
          Value: !Sub '${Redis}-001'
      MetricName: DatabaseMemoryUsagePercentage
      Namespace: AWS/ElastiCache
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Statistic: Sum
      Threshold: !Ref RedisMemoryUsedThreshold
      TreatMissingData: missing

  RedisCurrentConnectionsAlarm:
    Condition: AlarmEnabled
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Project}-${Environment}-CurrentConnections
      AlarmDescription: "CloudWatch alarm for concurrent and active connections."
      AlarmActions: 
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      InsufficientDataActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      OKActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AlarmSNSTopicName}'
      DatapointsToAlarm: 1
      Dimensions: 
        - Name: CacheClusterId
          Value: !Sub '${Redis}-001'
      MetricName: CurrConnections
      Namespace: AWS/ElastiCache
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 60
      Period: 60
      Statistic: Sum
      Threshold: !Ref CurrentConnectionsThreshold
      TreatMissingData: missing

Outputs:
  AuthSecret:
    Description: The ARN of Secret for Auth
    Value:
      Ref: AuthToken

  SecurityGroup:
    Description: The Security Group for incoming Redis connection
    Value:
      Ref: SecurityGroup

  Endpoint:
    Description: The endpoint for Redis
    Value:
      Fn::GetAtt:
      - Redis
      - PrimaryEndPoint.Address

  Port:
    Description: The port for Redis
    Value:
      Fn::GetAtt:
      - Redis
      - PrimaryEndPoint.Port
