AWSTemplateFormatVersion: '2010-09-09'
Description: SPID Hub - Orchestrator


Resources:
  myDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : Z08545153342W74OOLGU9
      Name: test-cross.fe.dev.pn.pagopa.it
      ResourceRecords:
      - '"ciaoooooooo"'
      TTL: 900
      Type: TXT


